'''
https://leetcode.com/problems/find-the-difference/
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"

'''

from collections import Counter
def findTheDifference(s: str, t: str):
    s_dict = Counter(s)
    t_dict = Counter(t)

    for key, value in t_dict.items():
        if s_dict[key] == 0 or s_dict[key] != t_dict[key]:
            return key
    return ""


print((findTheDifference("ae", "aea")))